apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow2
spec:
  templates:
    - name: main
      dag:
        tasks:
          - name: task1
            template: template-task1

          - name: task2
            template: template-task2
            depends: task1

          - name: task3
            template: template-task38
            depends: task2

          - name: task4
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task4
            depends: task2

          - name: task5
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: task5
            depends: task4

          - name: task6
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task6
            depends: task5

          - name: task7
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task78
            depends: task6

          - name: task8
            template: template-task38
            depends: task3.Succeeded && (task7 || task7.Failed || task7.Errored || task7.Omitted)

          - name: task9
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: task9-template
            depends: task8 && (task4.Failed || task6.Failed || task7.Failed)

          - name: task10
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task103
            depends: task2.Failed || task4.Failed || task5.Failed

          - name: task11
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task103
            depends: task6.Failed || task7.Failed

          - name: task12
            template: template-task103
            depends: task8 && task7

          - name: task13
            when: "{{tasks.task1.outputs.parameters.output1}} == false"
            template: template-task103
            depends: task3.Failed || task8.Failed

    - name: template-task1
      outputs:
        parameters:
          - name: output1
      container:
        image: x.azurecr.io/task1

    - name: template-task2
      container:
        image: x.azurecr.io/task2

    - name: template-task4
      outputs:
        artifacts:
          - name: artifact1
      container:
        image: x.azurecr.io/task4

    - name:  template-task6
      outputs:
        artifacts:
          - name: artifact2
      container:
        image: x.azurecr.io/task6

    - name: template-task78
      inputs:
        artifacts:
          - name: artifact2
      container:
        image: x.azurecr.io/task78

    - name: template-task38
      container:
        image: x.azurecr.io/task38

    - name: task9-template
      container:
        image: busybox

    - name: task5
      container:
        image: mcr.microsoft.com/azure-cli

    - name: template-task103
      container:
        image: x.azurecr.io/task103

  entrypoint: main
